# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 633579f907d73b961e7c3931fae598816297c30516e0ebef9bc1d233d5a36f4ffe1dd586777bbd9f73f2003a52424a78e1a6fd07276e8b3388b1d1ad8f5b6903

test:
  secret_key_base: 069a43bc175023568e272ac695e1449c4dd4ba9a02467de0c37493d4ff731538e78363c8fd38d64b15e300ff055240e2a08825836b79fe67fe24bd366466f003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
